# Generated by Django 4.2.11 on 2024-03-18 17:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('nominal_value', models.DecimalField(
                    decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(
                    decimal_places=5, max_digits=6)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('bank', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('iof', models.DecimalField(decimal_places=5,
                 default=Decimal('0.00'), max_digits=6)),
                ('insurance', models.DecimalField(
                    decimal_places=5, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='payments', to='api.loan')),
            ],
        ),
    ]
