# Generated by Django 4.2.11 on 2024-03-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='iof',
            new_name='iof_rate',
        ),
        migrations.AlterField(
            model_name='loan',
            name='request_date',
            field=models.DateField(),
        ),
    ]
