# Generated by Django 4.2.11 on 2024-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_iof_loan_iof_rate_alter_loan_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='insurance',
            new_name='insurance_rate',
        ),
        migrations.AlterField(
            model_name='loan',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
